/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Robots = {
  noIndex?: boolean;
  noFollow?: boolean;
};

export type Video = {
  url?: string;
  thumbnail?: Img;
  title?: string;
};

export type Button = {
  label?: string;
  url?: string;
};

export type HeroBackgroundSlideButton = {
  label?: string;
  url?: string;
};

export type DecorationImages = {
  whatWeDoInternational?: WhatWeDoInternational;
  whatWeDoPolish?: WhatWeDoPolish;
  cooperationInternationalEn?: CooperationInternationalEn;
  parentsCurrent?: ParentsCurrent;
  whatNewCurrent?: WhatNewCurrent;
};

export type AboutSectionButton = {
  label?: string;
  url?: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type ObjectFile = {
  asset?: SanityFileAssetReference;
  media?: unknown; // Unable to locate the referenced type "file.media" in schema
  _type: "file";
};

export type WhatWeDoInternational = {
  desktop?: Desktop;
  desktop2?: Desktop2;
  mobile?: Mobile;
  mobile2?: Mobile2;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Desktop = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "desktop.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type Desktop2 = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "desktop2.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type Mobile = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "mobile.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type Mobile2 = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "mobile2.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type WhatWeDoPolish = {
  desktop?: WhatWeDoPolishDesktop;
  mobile?: WhatWeDoPolishMobile;
};

export type WhatWeDoPolishDesktop = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "whatWeDoPolish.desktop.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type WhatWeDoPolishMobile = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "whatWeDoPolish.mobile.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type CooperationInternationalEn = {
  desktop?: CooperationInternationalEnDesktop;
};

export type CooperationInternationalEnDesktop = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "cooperationInternationalEn.desktop.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type ParentsCurrent = {
  desktop?: ParentsCurrentDesktop;
};

export type ParentsCurrentDesktop = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "parentsCurrent.desktop.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type WhatNewCurrent = {
  desktop?: WhatNewCurrentDesktop;
  mobile?: WhatNewCurrentMobile;
};

export type WhatNewCurrentDesktop = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "whatNewCurrent.desktop.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type WhatNewCurrentMobile = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "whatNewCurrent.mobile.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type PhotoInfoSectionButton = {
  text?: string;
  url?: string;
};

export type DonationCard = {
  title?: string;
  description?: string;
  accountNumber?: string;
  transferTitle?: string;
};

export type FundraisingCard = {
  title?: string;
  description?: string;
  buttonText?: string;
  buttonLink?: string;
};

export type VolunteerCard = {
  title?: string;
  description?: string;
  buttonText?: string;
  buttonLink?: string;
};

export type ObjectImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "object.image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type SliderObjectImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "slider.object.image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
};

export type Photo = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "photo.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
};

export type ExternalImage = {
  _type: "externalImage";
  url?: string;
};

export type Testimonial = {
  _type: "testimonial";
  text?: string;
  authorName?: string;
  authorRole?: string;
};

export type Partner = {
  _type: "partner";
  name?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  url?: string;
};

export type HeroBackgroundSlide = {
  _type: "heroBackgroundSlide";
  backgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  title?: string;
  description?: string;
  button?: HeroBackgroundSlideButton;
};

export type HeroSlide = {
  _type: "heroSlide";
  title?: string;
  description?: string;
  button?: Button;
  animatedImages?: Array<{
    image?: ObjectImage;
    position?: "center" | "top-right" | "bottom-left" | "bottom-right";
    _key: string;
  }>;
};

export type SupportImpactSection = {
  _type: "supportImpactSection";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  title?: string;
  description?: string;
  cards?: Array<{
    amount?: string;
    description?: string;
    color?: "blue" | "purple" | "pink" | "orange";
    _key: string;
  }>;
};

export type SupportOptionsSection = {
  _type: "supportOptionsSection";
  donationCard?: DonationCard;
  fundraisingCard?: FundraisingCard;
  volunteerCard?: VolunteerCard;
};

export type SupportHeroSection = {
  _type: "supportHeroSection";
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type CoalitionSection = {
  _type: "coalitionSection";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  title?: string;
  subtitle?: string;
  description?: string;
  cards?: Array<{
    title?: string;
    description?: string;
    _key: string;
  }>;
  buttonText?: string;
  buttonUrl?: string;
};

export type CooperationModelsSection = {
  _type: "cooperationModelsSection";
  title?: string;
  cards?: Array<{
    title?: string;
    description?: string;
    _key: string;
  }>;
};

export type InstitutionBenefitsSection = {
  _type: "institutionBenefitsSection";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  title?: string;
  subtitle?: string;
  description?: string;
  cardsTitle?: string;
  cards?: Array<{
    title?: string;
    description?: string;
    _key: string;
  }>;
  buttonText?: string;
  buttonUrl?: string;
};

export type AboutStatsSection = {
  _type: "aboutStatsSection";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  title?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  stats?: Array<{
    number?: string;
    label?: string;
    _key: string;
  }>;
};

export type TeacherEngagementSection = {
  _type: "teacherEngagementSection";
  title?: string;
  cards?: Array<{
    title?: string;
    description?: string;
    _key: string;
  }>;
  buttonText?: string;
  buttonUrl?: string;
  bottomImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type TeacherBenefitsSection = {
  _type: "teacherBenefitsSection";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  title?: string;
  subtitle?: string;
  description?: string;
  cards?: Array<{
    title?: string;
    description?: string;
    _key: string;
  }>;
  buttonText?: string;
  buttonUrl?: string;
};

export type CooperationCardsSection = {
  _type: "cooperationCardsSection";
  title?: string;
  subtitle?: string;
  cards?: Array<{
    title?: string;
    description?: string;
    buttonText?: string;
    buttonUrl?: string;
    _key: string;
  }>;
};

export type FaqAccordionSection = {
  _type: "faqAccordionSection";
  title?: string;
  subtitle?: string;
  questions?: Array<{
    question?: string;
    answer?: RichText;
    _key: string;
  }>;
};

export type PhotoInfoSection = {
  _type: "photoInfoSection";
  title?: string;
  photo?: Img;
  description?: RichText;
  button?: PhotoInfoSectionButton;
  decorImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  footerImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  footerImageMob?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type ProjectVideoSection = {
  _type: "projectVideoSection";
  title?: string;
  subtitle?: string;
  video?: Video;
  socialLinks?: Array<{
    platform?: "facebook" | "instagram" | "linkedin" | "twitter" | "youtube" | "tiktok" | "other";
    url?: string;
    label?: string;
    _key: string;
  }>;
};

export type ProjectQuestionsSection = {
  _type: "projectQuestionsSection";
  title?: string;
  subtitle?: string;
  questions?: Array<{
    question?: string;
    answer?: string;
    _key: string;
  }>;
};

export type ProjectPhotoInfoSection = {
  _type: "projectPhotoInfoSection";
  photo?: Img;
  title?: string;
  description?: RichText;
  buttonText?: string;
  buttonUrl?: string;
};

export type ProjectSignupSection = {
  _type: "projectSignupSection";
  title?: string;
  buttonText?: string;
  buttonUrl?: string;
};

export type ProjectFaqSection = {
  _type: "projectFaqSection";
  items?: Array<{
    question?: string;
    answer?: RichText;
    _key: string;
  }>;
};

export type PostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "post";
};

export type PostsGallerySection = {
  _type: "postsGallerySection";
  title?: string;
  subtitle?: string;
  variant?: "latest" | "next";
  posts?: Array<
    {
      _key: string;
    } & PostReference
  >;
  limit?: number;
  ctaText?: string;
  seeAllPostsText?: string;
  seeAllPostsUrl?: string;
  ctaVariant?: "primary" | "secondary";
  topImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  topImage2?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bottomImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  footerImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type ProjectsGallerySection = {
  _type: "projectsGallerySection";
  title?: string;
  subtitle?: string;
  projectFilter?: "all" | "polish" | "international" | "international_en";
  statusFilter?: "all" | "pending" | "active" | "completed";
  projects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
  limit?: number;
  ctaText?: string;
  ctaVariant?: "primary" | "secondary" | "link";
  seeAllProjectsText?: string;
  seeAllProjectsUrl?: string;
  decorationVariant?:
    | "what-we-do-international"
    | "what-we-do-polish"
    | "cooperation-international-en"
    | "what-new-current"
    | "parents-current";
  decorationImages?: DecorationImages;
};

export type ProjectTitleSection = {
  _type: "projectTitleSection";
  title?: string;
  description?: RichText;
  enabled?: boolean;
};

export type OurTeamSection = {
  _type: "ourTeamSection";
  enabled?: boolean;
  title?: string;
  subtitle?: string;
  employees?: Array<{
    photo?: Photo;
    name?: string;
    position?: string;
    bio?: string;
    _key: string;
  }>;
};

export type OurHistorySection = {
  _type: "ourHistorySection";
  enabled?: boolean;
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  bottomImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type WhoWeAreSection = {
  _type: "whoWeAreSection";
  enabled?: boolean;
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type WhatWeDoSection = {
  _type: "whatWeDoSection";
  enabled?: boolean;
  title?: string;
  subtitle?: string;
  subsubtitle?: string;
  descriptions?: Array<{
    heading?: string;
    description?: string;
    features?: Array<{
      description?: string;
      _key: string;
    }>;
    _key: string;
  }>;
  slider?: Array<{
    image?: SliderObjectImage;
    _key: string;
  }>;
};

export type DocumentsSection = {
  _type: "documentsSection";
  enabled?: boolean;
  backgroundColor?: "white" | "neutral-50" | "deep-navy-blue-50";
  title?: string;
  subtitle?: string;
  documents?: Array<{
    name?: string;
    description?: string;
    file?: ObjectFile;
    buttonText?: string;
    _key: string;
  }>;
};

export type ValuesSection = {
  _type: "valuesSection";
  enabled?: boolean;
  title?: string;
  values?: Array<{
    title?: string;
    subtitle?: string;
    description?: string;
    _key: string;
  }>;
};

export type TestimonialsSection = {
  _type: "testimonialsSection";
  enabled?: boolean;
  title?: string;
  subtitle?: string;
  testimonials?: Array<
    {
      _key: string;
    } & Testimonial
  >;
  bottomDoodle?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bottomImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type PartnersSection = {
  _type: "partnersSection";
  enabled?: boolean;
  title?: string;
  partners?: Array<
    {
      _key: string;
    } & Partner
  >;
};

export type AboutSection = {
  _type: "aboutSection";
  enabled?: boolean;
  title?: string;
  subtitle?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  button?: AboutSectionButton;
};

export type HeroBackgroundSection = {
  _type: "heroBackgroundSection";
  enabled?: boolean;
  slides?: Array<
    {
      _key: string;
    } & HeroBackgroundSlide
  >;
};

export type HeroSection = {
  _type: "heroSection";
  enabled?: boolean;
  slides?: Array<
    {
      _key: string;
    } & HeroSlide
  >;
};

export type PostsSection = {
  _type: "postsSection";
  displayNumber?: number;
};

export type LeadSection = {
  _type: "leadSection";
  title?: string;
  subtitle?: string;
};

export type Img = {
  _type: "img";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
};

export type RichText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }
  | ({
      _key: string;
    } & ExternalImage)
>;

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  canonical?: string;
  ogImage?: Img;
  twitterCreator?: string;
  robots?: Robots;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
};

export type IconPicker = {
  _type: "iconPicker";
  provider?: string;
  name?: string;
  svg?: string;
};

export type TranslationMetadata = {
  _id: string;
  _type: "translation.metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  translations?: InternationalizedArrayReference;
  schemaTypes?: Array<string>;
};

export type InternationalizedArrayReference = Array<
  {
    _key: string;
  } & InternationalizedArrayReferenceValue
>;

export type HomeReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "home";
};

export type ONasReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "oNas";
};

export type CoNowegoReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "coNowego";
};

export type CoRobimyReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "coRobimy";
};

export type DlaRodzicowReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "dlaRodzicow";
};

export type VolunteerWithUsReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "volunteerWithUs";
};

export type WspolpracaReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "wspolpraca";
};

export type Edukator_kaReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "edukator_ka";
};

export type DlaInstytucjiReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "dlaInstytucji";
};

export type WolontariatReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "wolontariat";
};

export type WesprzyjReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "wesprzyj";
};

export type FooterReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "footer";
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type TagReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tag";
};

export type InternationalizedArrayReferenceValue = {
  _type: "internationalizedArrayReferenceValue";
  value?:
    | HomeReference
    | ONasReference
    | CoNowegoReference
    | CoRobimyReference
    | DlaRodzicowReference
    | VolunteerWithUsReference
    | WspolpracaReference
    | Edukator_kaReference
    | DlaInstytucjiReference
    | WolontariatReference
    | WesprzyjReference
    | FooterReference
    | PostReference
    | ProjectReference
    | AuthorReference
    | CategoryReference
    | TagReference;
};

export type Tag = {
  _id: string;
  _type: "tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  name?: string;
  slug?: Slug;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  name?: string;
  slug?: Slug;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  seo?: Seo;
  title?: string;
  slug?: Slug;
  mainImage?: Img;
  shortDescription?: string;
  projectTypes?: "polish" | "international" | "international_en";
  projectStatus?: "pending" | "active" | "completed";
  startDate?: string;
  endDate?: string;
  sections?: Array<
    | ({
        _key: string;
      } & ProjectTitleSection)
    | ({
        _key: string;
      } & ProjectFaqSection)
    | ({
        _key: string;
      } & ProjectSignupSection)
    | ({
        _key: string;
      } & DocumentsSection)
    | ({
        _key: string;
      } & ProjectPhotoInfoSection)
    | ({
        _key: string;
      } & ProjectQuestionsSection)
    | ({
        _key: string;
      } & PartnersSection)
    | ({
        _key: string;
      } & ProjectVideoSection)
  >;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  title?: string;
  slug?: Slug;
  date?: string;
  modified?: string;
  status?:
    | "publish"
    | "future"
    | "draft"
    | "pending"
    | "private"
    | "trash"
    | "auto-draft"
    | "inherit";
  content?: RichText;
  excerpt?: RichText;
  featuredMedia?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  sticky?: boolean;
  author?: AuthorReference;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  tags?: Array<
    {
      _key: string;
    } & TagReference
  >;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  url?: string;
  description?: string;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  companyInfo?: {
    name?: string;
    street?: string;
    city?: string;
  };
  legalInfo?: {
    nip?: string;
    krs?: string;
    regon?: string;
  };
  bankAccount?: {
    bankName?: string;
    accountNumber?: string;
  };
  contact?: {
    email?: string;
    phones?: Array<string>;
  };
  socialMedia?: Array<{
    platform?: "facebook" | "instagram" | "linkedin" | "tiktok";
    url?: string;
    _key: string;
  }>;
};

export type Wesprzyj = {
  _id: string;
  _type: "wesprzyj";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  seo?: Seo;
  documentName?: string;
  sections?: Array<
    | ({
        _key: string;
      } & SupportHeroSection)
    | ({
        _key: string;
      } & SupportOptionsSection)
    | ({
        _key: string;
      } & SupportImpactSection)
  >;
};

export type Wolontariat = {
  _id: string;
  _type: "wolontariat";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  seo?: Seo;
  documentName?: string;
  sections?: Array<
    {
      _key: string;
    } & DocumentsSection
  >;
};

export type DlaInstytucji = {
  _id: string;
  _type: "dlaInstytucji";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  seo?: Seo;
  documentName?: string;
  sections?: Array<
    | ({
        _key: string;
      } & InstitutionBenefitsSection)
    | ({
        _key: string;
      } & CooperationModelsSection)
    | ({
        _key: string;
      } & PartnersSection)
    | ({
        _key: string;
      } & CoalitionSection)
    | ({
        _key: string;
      } & ValuesSection)
  >;
};

export type Edukator_ka = {
  _id: string;
  _type: "edukator_ka";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  seo?: Seo;
  documentName?: string;
  sections?: Array<
    | ({
        _key: string;
      } & TeacherBenefitsSection)
    | ({
        _key: string;
      } & TeacherEngagementSection)
    | ({
        _key: string;
      } & DocumentsSection)
  >;
};

export type Wspolpraca = {
  _id: string;
  _type: "wspolpraca";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  seo?: Seo;
  documentName?: string;
  sections?: Array<
    | ({
        _key: string;
      } & CooperationCardsSection)
    | ({
        _key: string;
      } & AboutStatsSection)
    | ({
        _key: string;
      } & PartnersSection)
    | ({
        _key: string;
      } & PostsGallerySection)
  >;
};

export type VolunteerWithUs = {
  _id: string;
  _type: "volunteerWithUs";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  seo?: Seo;
  documentName?: string;
  sections?: Array<
    | ({
        _key: string;
      } & ProjectsGallerySection)
    | ({
        _key: string;
      } & PartnersSection)
    | ({
        _key: string;
      } & PhotoInfoSection)
    | ({
        _key: string;
      } & FaqAccordionSection)
  >;
};

export type DlaRodzicow = {
  _id: string;
  _type: "dlaRodzicow";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  seo?: Seo;
  documentName?: string;
  sections?: Array<
    | ({
        _key: string;
      } & ProjectsGallerySection)
    | ({
        _key: string;
      } & FaqAccordionSection)
    | ({
        _key: string;
      } & TestimonialsSection)
    | ({
        _key: string;
      } & PhotoInfoSection)
    | ({
        _key: string;
      } & DocumentsSection)
  >;
};

export type CoRobimy = {
  _id: string;
  _type: "coRobimy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  seo?: Seo;
  documentName?: string;
  sections?: Array<
    | ({
        _key: string;
      } & ProjectsGallerySection)
    | ({
        _key: string;
      } & PhotoInfoSection)
    | ({
        _key: string;
      } & FaqAccordionSection)
  >;
};

export type CoNowego = {
  _id: string;
  _type: "coNowego";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  seo?: Seo;
  documentName?: string;
  sections?: Array<
    | ({
        _key: string;
      } & PostsGallerySection)
    | ({
        _key: string;
      } & ProjectsGallerySection)
  >;
};

export type ONas = {
  _id: string;
  _type: "oNas";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  seo?: Seo;
  documentName?: string;
  sections?: Array<
    | ({
        _key: string;
      } & HeroBackgroundSection)
    | ({
        _key: string;
      } & WhoWeAreSection)
    | ({
        _key: string;
      } & WhatWeDoSection)
    | ({
        _key: string;
      } & OurHistorySection)
    | ({
        _key: string;
      } & OurTeamSection)
    | ({
        _key: string;
      } & DocumentsSection)
  >;
};

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  seo?: Seo;
  documentName?: string;
  sections?: Array<
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & HeroBackgroundSection)
    | ({
        _key: string;
      } & ProjectsGallerySection)
    | ({
        _key: string;
      } & AboutSection)
    | ({
        _key: string;
      } & PartnersSection)
    | ({
        _key: string;
      } & TestimonialsSection)
    | ({
        _key: string;
      } & ValuesSection)
  >;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Robots
  | Video
  | Button
  | HeroBackgroundSlideButton
  | DecorationImages
  | AboutSectionButton
  | SanityFileAssetReference
  | ObjectFile
  | WhatWeDoInternational
  | SanityImageAssetReference
  | Desktop
  | Desktop2
  | Mobile
  | Mobile2
  | WhatWeDoPolish
  | WhatWeDoPolishDesktop
  | WhatWeDoPolishMobile
  | CooperationInternationalEn
  | CooperationInternationalEnDesktop
  | ParentsCurrent
  | ParentsCurrentDesktop
  | WhatNewCurrent
  | WhatNewCurrentDesktop
  | WhatNewCurrentMobile
  | PhotoInfoSectionButton
  | DonationCard
  | FundraisingCard
  | VolunteerCard
  | ObjectImage
  | SliderObjectImage
  | Photo
  | ExternalImage
  | Testimonial
  | Partner
  | HeroBackgroundSlide
  | HeroSlide
  | SupportImpactSection
  | SupportOptionsSection
  | SupportHeroSection
  | CoalitionSection
  | CooperationModelsSection
  | InstitutionBenefitsSection
  | AboutStatsSection
  | TeacherEngagementSection
  | TeacherBenefitsSection
  | CooperationCardsSection
  | FaqAccordionSection
  | PhotoInfoSection
  | ProjectVideoSection
  | ProjectQuestionsSection
  | ProjectPhotoInfoSection
  | ProjectSignupSection
  | ProjectFaqSection
  | PostReference
  | PostsGallerySection
  | ProjectReference
  | ProjectsGallerySection
  | ProjectTitleSection
  | OurTeamSection
  | OurHistorySection
  | WhoWeAreSection
  | WhatWeDoSection
  | DocumentsSection
  | ValuesSection
  | TestimonialsSection
  | PartnersSection
  | AboutSection
  | HeroBackgroundSection
  | HeroSection
  | PostsSection
  | LeadSection
  | Img
  | RichText
  | Seo
  | Settings
  | IconPicker
  | TranslationMetadata
  | InternationalizedArrayReference
  | HomeReference
  | ONasReference
  | CoNowegoReference
  | CoRobimyReference
  | DlaRodzicowReference
  | VolunteerWithUsReference
  | WspolpracaReference
  | Edukator_kaReference
  | DlaInstytucjiReference
  | WolontariatReference
  | WesprzyjReference
  | FooterReference
  | AuthorReference
  | CategoryReference
  | TagReference
  | InternationalizedArrayReferenceValue
  | Tag
  | Slug
  | Category
  | Project
  | Post
  | Author
  | SanityImageCrop
  | SanityImageHotspot
  | Footer
  | Wesprzyj
  | Wolontariat
  | DlaInstytucji
  | Edukator_ka
  | Wspolpraca
  | VolunteerWithUs
  | DlaRodzicow
  | CoRobimy
  | CoNowego
  | ONas
  | Home
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../web/sanity/queries/groq.example.ts
// Variable: FOOTER_QUERY
// Query: *[_type == "footer"][0]{  companyInfo,  legalInfo,  bankAccount,  contact,  socialMedia}
export type FOOTER_QUERY_RESULT = {
  companyInfo: {
    name?: string;
    street?: string;
    city?: string;
  } | null;
  legalInfo: {
    nip?: string;
    krs?: string;
    regon?: string;
  } | null;
  bankAccount: {
    bankName?: string;
    accountNumber?: string;
  } | null;
  contact: {
    email?: string;
    phones?: Array<string>;
  } | null;
  socialMedia: Array<{
    platform?: "facebook" | "instagram" | "linkedin" | "tiktok";
    url?: string;
    _key: string;
  }> | null;
} | null;

// Source: ../web/sanity/queries/posts.ts
// Variable: POST_BY_ID_QUERY
// Query: *[_id == $postId][0]{  _id,  title,  slug,  date,  modified,  status,  content,  excerpt,  featuredMedia,  sticky,  author->{    _id,    name,    slug  },  categories[]->{    _id,    name,    slug  },  tags[]->{    _id,    name,    slug  }}
export type POST_BY_ID_QUERY_RESULT =
  | {
      _id: string;
      title: null;
      slug: null;
      date: null;
      modified: null;
      status: null;
      content: null;
      excerpt: null;
      featuredMedia: null;
      sticky: null;
      author: null;
      categories: null;
      tags: null;
    }
  | {
      _id: string;
      title: string | null;
      slug: null;
      date: null;
      modified: null;
      status: null;
      content: null;
      excerpt: null;
      featuredMedia: null;
      sticky: null;
      author: null;
      categories: null;
      tags: null;
    }
  | {
      _id: string;
      title: null;
      slug: Slug | null;
      date: null;
      modified: null;
      status: null;
      content: null;
      excerpt: null;
      featuredMedia: null;
      sticky: null;
      author: null;
      categories: null;
      tags: null;
    }
  | {
      _id: string;
      title: string | null;
      slug: Slug | null;
      date: null;
      modified: null;
      status: null;
      content: null;
      excerpt: null;
      featuredMedia: null;
      sticky: null;
      author: null;
      categories: null;
      tags: null;
    }
  | {
      _id: string;
      title: string | null;
      slug: Slug | null;
      date: string | null;
      modified: string | null;
      status:
        | "auto-draft"
        | "draft"
        | "future"
        | "inherit"
        | "pending"
        | "private"
        | "publish"
        | "trash"
        | null;
      content: RichText | null;
      excerpt: RichText | null;
      featuredMedia: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      sticky: boolean | null;
      author: {
        _id: string;
        name: string | null;
        slug: Slug | null;
      } | null;
      categories: Array<{
        _id: string;
        name: string | null;
        slug: Slug | null;
      }> | null;
      tags: Array<{
        _id: string;
        name: string | null;
        slug: Slug | null;
      }> | null;
    }
  | null;

// Source: ../web/sanity/queries/projects.ts
// Variable: PROJECT_BY_ID_QUERY
// Query: *[_id == $projectId][0]{  _id,  title,  slug,  mainImage,  shortDescription,  startDate,  projectTypes,  projectStatus,  sections}
export type PROJECT_BY_ID_QUERY_RESULT =
  | {
      _id: string;
      title: null;
      slug: null;
      mainImage: null;
      shortDescription: null;
      startDate: null;
      projectTypes: null;
      projectStatus: null;
      sections: null;
    }
  | {
      _id: string;
      title: string | null;
      slug: null;
      mainImage: null;
      shortDescription: null;
      startDate: null;
      projectTypes: null;
      projectStatus: null;
      sections: null;
    }
  | {
      _id: string;
      title: null;
      slug: Slug | null;
      mainImage: null;
      shortDescription: null;
      startDate: null;
      projectTypes: null;
      projectStatus: null;
      sections: null;
    }
  | {
      _id: string;
      title: string | null;
      slug: Slug | null;
      mainImage: null;
      shortDescription: null;
      startDate: null;
      projectTypes: null;
      projectStatus: null;
      sections: null;
    }
  | {
      _id: string;
      title: null;
      slug: null;
      mainImage: null;
      shortDescription: null;
      startDate: null;
      projectTypes: null;
      projectStatus: null;
      sections: Array<
        {
          _key: string;
        } & DocumentsSection
      > | null;
    }
  | {
      _id: string;
      title: null;
      slug: null;
      mainImage: null;
      shortDescription: null;
      startDate: null;
      projectTypes: null;
      projectStatus: null;
      sections: Array<
        | ({
            _key: string;
          } & AboutSection)
        | ({
            _key: string;
          } & HeroBackgroundSection)
        | ({
            _key: string;
          } & HeroSection)
        | ({
            _key: string;
          } & PartnersSection)
        | ({
            _key: string;
          } & ProjectsGallerySection)
        | ({
            _key: string;
          } & TestimonialsSection)
        | ({
            _key: string;
          } & ValuesSection)
      > | null;
    }
  | {
      _id: string;
      title: null;
      slug: null;
      mainImage: null;
      shortDescription: null;
      startDate: null;
      projectTypes: null;
      projectStatus: null;
      sections: Array<
        | ({
            _key: string;
          } & AboutStatsSection)
        | ({
            _key: string;
          } & CooperationCardsSection)
        | ({
            _key: string;
          } & PartnersSection)
        | ({
            _key: string;
          } & PostsGallerySection)
      > | null;
    }
  | {
      _id: string;
      title: null;
      slug: null;
      mainImage: null;
      shortDescription: null;
      startDate: null;
      projectTypes: null;
      projectStatus: null;
      sections: Array<
        | ({
            _key: string;
          } & CoalitionSection)
        | ({
            _key: string;
          } & CooperationModelsSection)
        | ({
            _key: string;
          } & InstitutionBenefitsSection)
        | ({
            _key: string;
          } & PartnersSection)
        | ({
            _key: string;
          } & ValuesSection)
      > | null;
    }
  | {
      _id: string;
      title: null;
      slug: null;
      mainImage: null;
      shortDescription: null;
      startDate: null;
      projectTypes: null;
      projectStatus: null;
      sections: Array<
        | ({
            _key: string;
          } & DocumentsSection)
        | ({
            _key: string;
          } & FaqAccordionSection)
        | ({
            _key: string;
          } & PhotoInfoSection)
        | ({
            _key: string;
          } & ProjectsGallerySection)
        | ({
            _key: string;
          } & TestimonialsSection)
      > | null;
    }
  | {
      _id: string;
      title: null;
      slug: null;
      mainImage: null;
      shortDescription: null;
      startDate: null;
      projectTypes: null;
      projectStatus: null;
      sections: Array<
        | ({
            _key: string;
          } & DocumentsSection)
        | ({
            _key: string;
          } & HeroBackgroundSection)
        | ({
            _key: string;
          } & OurHistorySection)
        | ({
            _key: string;
          } & OurTeamSection)
        | ({
            _key: string;
          } & WhatWeDoSection)
        | ({
            _key: string;
          } & WhoWeAreSection)
      > | null;
    }
  | {
      _id: string;
      title: null;
      slug: null;
      mainImage: null;
      shortDescription: null;
      startDate: null;
      projectTypes: null;
      projectStatus: null;
      sections: Array<
        | ({
            _key: string;
          } & DocumentsSection)
        | ({
            _key: string;
          } & TeacherBenefitsSection)
        | ({
            _key: string;
          } & TeacherEngagementSection)
      > | null;
    }
  | {
      _id: string;
      title: null;
      slug: null;
      mainImage: null;
      shortDescription: null;
      startDate: null;
      projectTypes: null;
      projectStatus: null;
      sections: Array<
        | ({
            _key: string;
          } & FaqAccordionSection)
        | ({
            _key: string;
          } & PartnersSection)
        | ({
            _key: string;
          } & PhotoInfoSection)
        | ({
            _key: string;
          } & ProjectsGallerySection)
      > | null;
    }
  | {
      _id: string;
      title: null;
      slug: null;
      mainImage: null;
      shortDescription: null;
      startDate: null;
      projectTypes: null;
      projectStatus: null;
      sections: Array<
        | ({
            _key: string;
          } & FaqAccordionSection)
        | ({
            _key: string;
          } & PhotoInfoSection)
        | ({
            _key: string;
          } & ProjectsGallerySection)
      > | null;
    }
  | {
      _id: string;
      title: null;
      slug: null;
      mainImage: null;
      shortDescription: null;
      startDate: null;
      projectTypes: null;
      projectStatus: null;
      sections: Array<
        | ({
            _key: string;
          } & PostsGallerySection)
        | ({
            _key: string;
          } & ProjectsGallerySection)
      > | null;
    }
  | {
      _id: string;
      title: null;
      slug: null;
      mainImage: null;
      shortDescription: null;
      startDate: null;
      projectTypes: null;
      projectStatus: null;
      sections: Array<
        | ({
            _key: string;
          } & SupportHeroSection)
        | ({
            _key: string;
          } & SupportImpactSection)
        | ({
            _key: string;
          } & SupportOptionsSection)
      > | null;
    }
  | {
      _id: string;
      title: string | null;
      slug: Slug | null;
      mainImage: Img | null;
      shortDescription: string | null;
      startDate: string | null;
      projectTypes: "international_en" | "international" | "polish" | null;
      projectStatus: "active" | "completed" | "pending" | null;
      sections: Array<
        | ({
            _key: string;
          } & DocumentsSection)
        | ({
            _key: string;
          } & PartnersSection)
        | ({
            _key: string;
          } & ProjectFaqSection)
        | ({
            _key: string;
          } & ProjectPhotoInfoSection)
        | ({
            _key: string;
          } & ProjectQuestionsSection)
        | ({
            _key: string;
          } & ProjectSignupSection)
        | ({
            _key: string;
          } & ProjectTitleSection)
        | ({
            _key: string;
          } & ProjectVideoSection)
      > | null;
    }
  | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "footer"][0]{\n  companyInfo,\n  legalInfo,\n  bankAccount,\n  contact,\n  socialMedia\n}': FOOTER_QUERY_RESULT;
    "*[_id == $postId][0]{\n  _id,\n  title,\n  slug,\n  date,\n  modified,\n  status,\n  content,\n  excerpt,\n  featuredMedia,\n  sticky,\n  author->{\n    _id,\n    name,\n    slug\n  },\n  categories[]->{\n    _id,\n    name,\n    slug\n  },\n  tags[]->{\n    _id,\n    name,\n    slug\n  }\n}": POST_BY_ID_QUERY_RESULT;
    "*[_id == $projectId][0]{\n  _id,\n  title,\n  slug,\n  mainImage,\n  shortDescription,\n  startDate,\n  projectTypes,\n  projectStatus,\n  sections\n}": PROJECT_BY_ID_QUERY_RESULT;
  }
}
