/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Robots = {
  noIndex?: boolean;
  noFollow?: boolean;
};

export type Video = {
  url?: string;
  thumbnail?: Img;
  title?: string;
};

export type Button = {
  label?: string;
  url?: string;
};

export type HeroBackgroundSlideButton = {
  label?: string;
  url?: string;
};

export type AboutSectionButton = {
  label?: string;
  url?: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type ObjectFile = {
  asset?: SanityFileAssetReference;
  media?: unknown; // Unable to locate the referenced type "file.media" in schema
  _type: "file";
};

export type PhotoInfoSectionButton = {
  text?: string;
  url?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ObjectImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type SliderObjectImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "object.image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
};

export type Photo = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "photo.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
};

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  companyInfo?: {
    name?: string;
    street?: string;
    city?: string;
  };
  legalInfo?: {
    nip?: string;
    krs?: string;
    regon?: string;
  };
  bankAccount?: {
    bankName?: string;
    accountNumber?: string;
  };
  contact?: {
    email?: string;
    phones?: Array<string>;
  };
  socialMedia?: Array<{
    platform?: "facebook" | "instagram" | "linkedin" | "tiktok";
    url?: string;
    _key: string;
  }>;
};

export type Testimonial = {
  _type: "testimonial";
  text?: string;
  authorName?: string;
  authorRole?: string;
};

export type Partner = {
  _type: "partner";
  name?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  url?: string;
};

export type HeroBackgroundSlide = {
  _type: "heroBackgroundSlide";
  backgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  title?: string;
  description?: string;
  button?: HeroBackgroundSlideButton;
};

export type HeroSlide = {
  _type: "heroSlide";
  title?: string;
  description?: string;
  button?: Button;
  animatedImages?: Array<{
    image?: ObjectImage;
    position?: "center" | "top-right" | "bottom-left" | "bottom-right";
    _key: string;
  }>;
};

export type FaqAccordionSection = {
  _type: "faqAccordionSection";
  title?: string;
  subtitle?: string;
  questions?: Array<{
    question?: string;
    answer?: RichText;
    _key: string;
  }>;
};

export type PhotoInfoSection = {
  _type: "photoInfoSection";
  title?: string;
  photo?: Img;
  description?: RichText;
  button?: PhotoInfoSectionButton;
};

export type ProjectVideoSection = {
  _type: "projectVideoSection";
  title?: string;
  subtitle?: string;
  video?: Video;
  socialLinks?: Array<{
    platform?: "facebook" | "instagram" | "linkedin" | "twitter" | "youtube" | "tiktok" | "other";
    url?: string;
    label?: string;
    _key: string;
  }>;
};

export type ProjectQuestionsSection = {
  _type: "projectQuestionsSection";
  questions?: Array<{
    question?: string;
    answer?: string;
    _key: string;
  }>;
};

export type ProjectPhotoInfoSection = {
  _type: "projectPhotoInfoSection";
  photo?: Img;
  title?: string;
  description?: RichText;
  buttonText?: string;
  buttonUrl?: string;
};

export type ProjectSignupSection = {
  _type: "projectSignupSection";
  title?: string;
  buttonText?: string;
  buttonUrl?: string;
};

export type ProjectFaqSection = {
  _type: "projectFaqSection";
  items?: Array<{
    question?: string;
    answer?: RichText;
    _key: string;
  }>;
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type ProjectsGallerySection = {
  _type: "projectsGallerySection";
  title?: string;
  subtitle?: string;
  projectFilter?: "all" | "polish" | "international";
  statusFilter?: "all" | "pending" | "active" | "completed";
  projects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
  limit?: number;
  ctaText?: string;
  ctaVariant?: "primary" | "secondary" | "link";
  seeAllProjectsText?: string;
  seeAllProjectsUrl?: string;
};

export type ProjectTitleSection = {
  _type: "projectTitleSection";
  title?: string;
  description?: RichText;
  enabled?: boolean;
};

export type OurTeamSection = {
  _type: "ourTeamSection";
  enabled?: boolean;
  title?: string;
  subtitle?: string;
  employees?: Array<{
    photo?: Photo;
    name?: string;
    position?: string;
    bio?: string;
    _key: string;
  }>;
};

export type OurHistorySection = {
  _type: "ourHistorySection";
  enabled?: boolean;
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type WhoWeAreSection = {
  _type: "whoWeAreSection";
  enabled?: boolean;
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type WhatWeDoSection = {
  _type: "whatWeDoSection";
  enabled?: boolean;
  title?: string;
  subtitle?: string;
  subsubtitle?: string;
  descriptions?: Array<{
    description?: RichText;
    _key: string;
  }>;
  slider?: Array<{
    image?: SliderObjectImage;
    _key: string;
  }>;
};

export type DocumentsSection = {
  _type: "documentsSection";
  enabled?: boolean;
  title?: string;
  subtitle?: string;
  documents?: Array<{
    name?: string;
    description?: string;
    file?: ObjectFile;
    buttonText?: string;
    _key: string;
  }>;
};

export type ValuesSection = {
  _type: "valuesSection";
  enabled?: boolean;
  title?: string;
  values?: Array<{
    title?: string;
    subtitle?: string;
    description?: string;
    _key: string;
  }>;
};

export type TestimonialsSection = {
  _type: "testimonialsSection";
  enabled?: boolean;
  title?: string;
  subtitle?: string;
  testimonials?: Array<
    {
      _key: string;
    } & Testimonial
  >;
};

export type PartnersSection = {
  _type: "partnersSection";
  enabled?: boolean;
  title?: string;
  partners?: Array<
    {
      _key: string;
    } & Partner
  >;
};

export type AboutSection = {
  _type: "aboutSection";
  enabled?: boolean;
  title?: string;
  subtitle?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  button?: AboutSectionButton;
};

export type HeroBackgroundSection = {
  _type: "heroBackgroundSection";
  enabled?: boolean;
  slides?: Array<
    {
      _key: string;
    } & HeroBackgroundSlide
  >;
};

export type HeroSection = {
  _type: "heroSection";
  enabled?: boolean;
  slides?: Array<
    {
      _key: string;
    } & HeroSlide
  >;
};

export type PostsSection = {
  _type: "postsSection";
  displayNumber?: number;
};

export type LeadSection = {
  _type: "leadSection";
  title?: string;
  subtitle?: string;
};

export type Img = {
  _type: "img";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
};

export type RichText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  canonical?: string;
  ogImage?: Img;
  twitterCreator?: string;
  robots?: Robots;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  icon?: IconPicker;
};

export type IconPicker = {
  _type: "iconPicker";
  provider?: string;
  name?: string;
  svg?: string;
};

export type TranslationMetadata = {
  _id: string;
  _type: "translation.metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  translations?: InternationalizedArrayReference;
  schemaTypes?: Array<string>;
};

export type InternationalizedArrayReference = Array<
  {
    _key: string;
  } & InternationalizedArrayReferenceValue
>;

export type HomeReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "home";
};

export type ONasReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "oNas";
};

export type CoNowegoReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "coNowego";
};

export type CoRobimyReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "coRobimy";
};

export type DlaRodzicowReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "dlaRodzicow";
};

export type VolunteerWithUsReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "volunteerWithUs";
};

export type WspolpracaReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "wspolpraca";
};

export type WesprzyjReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "wesprzyj";
};

export type PostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "post";
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type InternationalizedArrayReferenceValue = {
  _type: "internationalizedArrayReferenceValue";
  value?:
    | HomeReference
    | ONasReference
    | CoNowegoReference
    | CoRobimyReference
    | DlaRodzicowReference
    | VolunteerWithUsReference
    | WspolpracaReference
    | WesprzyjReference
    | PostReference
    | ProjectReference
    | AuthorReference;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  seo?: Seo;
  title?: string;
  slug?: Slug;
  mainImage?: Img;
  shortDescription?: string;
  projectTypes?: "polish" | "international";
  projectStatus?: "pending" | "active" | "completed";
  startDate?: string;
  endDate?: string;
  sections?: Array<
    | ({
        _key: string;
      } & ProjectTitleSection)
    | ({
        _key: string;
      } & ProjectFaqSection)
    | ({
        _key: string;
      } & ProjectSignupSection)
    | ({
        _key: string;
      } & DocumentsSection)
    | ({
        _key: string;
      } & ProjectPhotoInfoSection)
    | ({
        _key: string;
      } & ProjectQuestionsSection)
    | ({
        _key: string;
      } & PartnersSection)
    | ({
        _key: string;
      } & ProjectVideoSection)
  >;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  seo?: Seo;
  title?: string;
  slug?: Slug;
  author?: AuthorReference;
  image?: Img;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  publishedAt?: string;
  body?: RichText;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  name?: string;
  slug?: Slug;
  img?: Img;
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Wesprzyj = {
  _id: string;
  _type: "wesprzyj";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  seo?: Seo;
  documentName?: string;
  sections?: Array<
    {
      _key: string;
    } & HeroSection
  >;
};

export type Wspolpraca = {
  _id: string;
  _type: "wspolpraca";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  seo?: Seo;
  documentName?: string;
  sections?: Array<
    {
      _key: string;
    } & HeroSection
  >;
};

export type VolunteerWithUs = {
  _id: string;
  _type: "volunteerWithUs";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  seo?: Seo;
  documentName?: string;
  sections?: Array<
    {
      _key: string;
    } & HeroSection
  >;
};

export type DlaRodzicow = {
  _id: string;
  _type: "dlaRodzicow";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  seo?: Seo;
  documentName?: string;
  sections?: Array<
    | ({
        _key: string;
      } & ProjectsGallerySection)
    | ({
        _key: string;
      } & FaqAccordionSection)
    | ({
        _key: string;
      } & TestimonialsSection)
    | ({
        _key: string;
      } & PhotoInfoSection)
    | ({
        _key: string;
      } & DocumentsSection)
  >;
};

export type CoRobimy = {
  _id: string;
  _type: "coRobimy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  seo?: Seo;
  documentName?: string;
  sections?: Array<
    | ({
        _key: string;
      } & ProjectsGallerySection)
    | ({
        _key: string;
      } & PhotoInfoSection)
    | ({
        _key: string;
      } & FaqAccordionSection)
  >;
};

export type CoNowego = {
  _id: string;
  _type: "coNowego";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  seo?: Seo;
  documentName?: string;
  sections?: Array<
    {
      _key: string;
    } & ProjectsGallerySection
  >;
};

export type ONas = {
  _id: string;
  _type: "oNas";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  seo?: Seo;
  documentName?: string;
  sections?: Array<
    | ({
        _key: string;
      } & HeroBackgroundSection)
    | ({
        _key: string;
      } & WhoWeAreSection)
    | ({
        _key: string;
      } & WhatWeDoSection)
    | ({
        _key: string;
      } & OurHistorySection)
    | ({
        _key: string;
      } & OurTeamSection)
    | ({
        _key: string;
      } & DocumentsSection)
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  seo?: Seo;
  documentName?: string;
  sections?: Array<
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & HeroBackgroundSection)
    | ({
        _key: string;
      } & ProjectsGallerySection)
    | ({
        _key: string;
      } & AboutSection)
    | ({
        _key: string;
      } & PartnersSection)
    | ({
        _key: string;
      } & TestimonialsSection)
    | ({
        _key: string;
      } & ValuesSection)
  >;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Robots
  | Video
  | Button
  | HeroBackgroundSlideButton
  | AboutSectionButton
  | SanityFileAssetReference
  | ObjectFile
  | PhotoInfoSectionButton
  | SanityImageAssetReference
  | ObjectImage
  | SliderObjectImage
  | Photo
  | Footer
  | Testimonial
  | Partner
  | HeroBackgroundSlide
  | HeroSlide
  | FaqAccordionSection
  | PhotoInfoSection
  | ProjectVideoSection
  | ProjectQuestionsSection
  | ProjectPhotoInfoSection
  | ProjectSignupSection
  | ProjectFaqSection
  | ProjectReference
  | ProjectsGallerySection
  | ProjectTitleSection
  | OurTeamSection
  | OurHistorySection
  | WhoWeAreSection
  | WhatWeDoSection
  | DocumentsSection
  | ValuesSection
  | TestimonialsSection
  | PartnersSection
  | AboutSection
  | HeroBackgroundSection
  | HeroSection
  | PostsSection
  | LeadSection
  | Img
  | RichText
  | Seo
  | Settings
  | Category
  | IconPicker
  | TranslationMetadata
  | InternationalizedArrayReference
  | HomeReference
  | ONasReference
  | CoNowegoReference
  | CoRobimyReference
  | DlaRodzicowReference
  | VolunteerWithUsReference
  | WspolpracaReference
  | WesprzyjReference
  | PostReference
  | AuthorReference
  | InternationalizedArrayReferenceValue
  | Project
  | Slug
  | CategoryReference
  | Post
  | Author
  | Wesprzyj
  | Wspolpraca
  | VolunteerWithUs
  | DlaRodzicow
  | CoRobimy
  | CoNowego
  | ONas
  | SanityImageCrop
  | SanityImageHotspot
  | Home
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../web/sanity/queries/groq.example.ts
// Variable: FOOTER_QUERY
// Query: *[_type == "footer"][0]{  companyInfo,  legalInfo,  bankAccount,  contact,  socialMedia}
export type FOOTER_QUERY_RESULT = {
  companyInfo: {
    name?: string;
    street?: string;
    city?: string;
  } | null;
  legalInfo: {
    nip?: string;
    krs?: string;
    regon?: string;
  } | null;
  bankAccount: {
    bankName?: string;
    accountNumber?: string;
  } | null;
  contact: {
    email?: string;
    phones?: Array<string>;
  } | null;
  socialMedia: Array<{
    platform?: "facebook" | "instagram" | "linkedin" | "tiktok";
    url?: string;
    _key: string;
  }> | null;
} | null;

// Source: ../web/sanity/queries/projects.ts
// Variable: PROJECT_BY_ID_QUERY
// Query: *[_id == $projectId][0]{  _id,  title,  slug,  mainImage,  shortDescription,  startDate,  projectTypes,  projectStatus,  sections}
export type PROJECT_BY_ID_QUERY_RESULT =
  | {
      _id: string;
      title: null;
      slug: null;
      mainImage: null;
      shortDescription: null;
      startDate: null;
      projectTypes: null;
      projectStatus: null;
      sections: null;
    }
  | {
      _id: string;
      title: string | null;
      slug: null;
      mainImage: null;
      shortDescription: null;
      startDate: null;
      projectTypes: null;
      projectStatus: null;
      sections: null;
    }
  | {
      _id: string;
      title: null;
      slug: Slug | null;
      mainImage: null;
      shortDescription: null;
      startDate: null;
      projectTypes: null;
      projectStatus: null;
      sections: null;
    }
  | {
      _id: string;
      title: string | null;
      slug: Slug | null;
      mainImage: null;
      shortDescription: null;
      startDate: null;
      projectTypes: null;
      projectStatus: null;
      sections: null;
    }
  | {
      _id: string;
      title: null;
      slug: null;
      mainImage: null;
      shortDescription: null;
      startDate: null;
      projectTypes: null;
      projectStatus: null;
      sections: Array<
        {
          _key: string;
        } & HeroSection
      > | null;
    }
  | {
      _id: string;
      title: null;
      slug: null;
      mainImage: null;
      shortDescription: null;
      startDate: null;
      projectTypes: null;
      projectStatus: null;
      sections: Array<
        {
          _key: string;
        } & ProjectsGallerySection
      > | null;
    }
  | {
      _id: string;
      title: null;
      slug: null;
      mainImage: null;
      shortDescription: null;
      startDate: null;
      projectTypes: null;
      projectStatus: null;
      sections: Array<
        | ({
            _key: string;
          } & AboutSection)
        | ({
            _key: string;
          } & HeroBackgroundSection)
        | ({
            _key: string;
          } & HeroSection)
        | ({
            _key: string;
          } & PartnersSection)
        | ({
            _key: string;
          } & ProjectsGallerySection)
        | ({
            _key: string;
          } & TestimonialsSection)
        | ({
            _key: string;
          } & ValuesSection)
      > | null;
    }
  | {
      _id: string;
      title: null;
      slug: null;
      mainImage: null;
      shortDescription: null;
      startDate: null;
      projectTypes: null;
      projectStatus: null;
      sections: Array<
        | ({
            _key: string;
          } & DocumentsSection)
        | ({
            _key: string;
          } & FaqAccordionSection)
        | ({
            _key: string;
          } & PhotoInfoSection)
        | ({
            _key: string;
          } & ProjectsGallerySection)
        | ({
            _key: string;
          } & TestimonialsSection)
      > | null;
    }
  | {
      _id: string;
      title: null;
      slug: null;
      mainImage: null;
      shortDescription: null;
      startDate: null;
      projectTypes: null;
      projectStatus: null;
      sections: Array<
        | ({
            _key: string;
          } & DocumentsSection)
        | ({
            _key: string;
          } & HeroBackgroundSection)
        | ({
            _key: string;
          } & OurHistorySection)
        | ({
            _key: string;
          } & OurTeamSection)
        | ({
            _key: string;
          } & WhatWeDoSection)
        | ({
            _key: string;
          } & WhoWeAreSection)
      > | null;
    }
  | {
      _id: string;
      title: null;
      slug: null;
      mainImage: null;
      shortDescription: null;
      startDate: null;
      projectTypes: null;
      projectStatus: null;
      sections: Array<
        | ({
            _key: string;
          } & FaqAccordionSection)
        | ({
            _key: string;
          } & PhotoInfoSection)
        | ({
            _key: string;
          } & ProjectsGallerySection)
      > | null;
    }
  | {
      _id: string;
      title: string | null;
      slug: Slug | null;
      mainImage: Img | null;
      shortDescription: string | null;
      startDate: string | null;
      projectTypes: "international" | "polish" | null;
      projectStatus: "active" | "completed" | "pending" | null;
      sections: Array<
        | ({
            _key: string;
          } & DocumentsSection)
        | ({
            _key: string;
          } & PartnersSection)
        | ({
            _key: string;
          } & ProjectFaqSection)
        | ({
            _key: string;
          } & ProjectPhotoInfoSection)
        | ({
            _key: string;
          } & ProjectQuestionsSection)
        | ({
            _key: string;
          } & ProjectSignupSection)
        | ({
            _key: string;
          } & ProjectTitleSection)
        | ({
            _key: string;
          } & ProjectVideoSection)
      > | null;
    }
  | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "footer"][0]{\n  companyInfo,\n  legalInfo,\n  bankAccount,\n  contact,\n  socialMedia\n}': FOOTER_QUERY_RESULT;
    "*[_id == $projectId][0]{\n  _id,\n  title,\n  slug,\n  mainImage,\n  shortDescription,\n  startDate,\n  projectTypes,\n  projectStatus,\n  sections\n}": PROJECT_BY_ID_QUERY_RESULT;
  }
}
